{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andrei1058.bedwars.bedwars-api",
    "module": "bedwars-api",
    "version": "22.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bedwars-api-22.3-SNAPSHOT.jar",
          "url": "bedwars-api-22.3-SNAPSHOT.jar",
          "size": 113165,
          "sha512": "c941acd082859d982a78962f3387395440b2b323e53b7fd4b60adf8edb2fa3ba22826a03570f537687eade04aa5a84c06e852fdec958d2e7e790e6457850dad8",
          "sha256": "5bf60f8c3189755922eec63345fa090061e3debdef40c6f0e44fbc38c957bd42",
          "sha1": "768c6cc80302fc018d4afaf37d69c12c43f9b917",
          "md5": "abda7b0f676a45e58f958b3d1f1d76cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bedwars-api-22.3-SNAPSHOT.jar",
          "url": "bedwars-api-22.3-SNAPSHOT.jar",
          "size": 113165,
          "sha512": "c941acd082859d982a78962f3387395440b2b323e53b7fd4b60adf8edb2fa3ba22826a03570f537687eade04aa5a84c06e852fdec958d2e7e790e6457850dad8",
          "sha256": "5bf60f8c3189755922eec63345fa090061e3debdef40c6f0e44fbc38c957bd42",
          "sha1": "768c6cc80302fc018d4afaf37d69c12c43f9b917",
          "md5": "abda7b0f676a45e58f958b3d1f1d76cd"
        }
      ]
    }
  ]
}
